In [1]:
import pandas as pd
import seaborn as sns

In [2]:
df = pd.read_csv('./data/oral_cancer_prediction_dataset.csv')

In [3]:
df.head()

,ID,Country,Age,Gender,Tobacco Use,Alcohol Consumption,HPV Infection,Betel Quid Use,Chronic Sun Exposure,Poor Oral Hygiene,...,Difficulty Swallowing,White or Red Patches in Mouth,Tumor Size (cm),Cancer Stage,Treatment Type,"Survival Rate (5-Year, %)",Cost of Treatment (USD),Economic Burden (Lost Workdays per Year),Early Diagnosis,Oral Cancer (Diagnosis)
0,1,Italy,36,Female,Yes,Yes,Yes,No,No,Yes,...,No,No,0.000000,0,No Treatment,100.000000,0.00,0,No,No
1,2,Japan,64,Male,Yes,Yes,Yes,No,Yes,Yes,...,No,No,1.782186,1,No Treatment,83.340103,77772.50,177,No,Yes
2,3,UK,37,Female,No,Yes,No,No,Yes,Yes,...,No,Yes,3.523895,2,Surgery,63.222871,101164.50,130,Yes,Yes
3,4,Sri Lanka,55,Male,Yes,Yes,No,Yes,No,Yes,...,No,No,0.000000,0,No Treatment,100.000000,0.00,0,Yes,No
4,5,South Africa,68,Male,No,No,No,No,No,Yes,...,No,No,2.834789,3,No Treatment,44.293199,45354.75,52,No,Yes

In [4]:
(df.isnull().sum() * 100) / len(df['ID'])

ID                                          0.0
Country                                     0.0
Age                                         0.0
Gender                                      0.0
Tobacco Use                                 0.0
Alcohol Consumption                         0.0
HPV Infection                               0.0
Betel Quid Use                              0.0
Chronic Sun Exposure                        0.0
Poor Oral Hygiene                           0.0
Diet (Fruits & Vegetables Intake)           0.0
Family History of Cancer                    0.0
Compromised Immune System                   0.0
Oral Lesions                                0.0
Unexplained Bleeding                        0.0
Difficulty Swallowing                       0.0
White or Red Patches in Mouth               0.0
Tumor Size (cm)                             0.0
Cancer Stage                                0.0
Treatment Type                              0.0
Survival Rate (5-Year, %)                   0.0
Cost of Treatment (USD)                     0.0
Economic Burden (Lost Workdays per Year)    0.0
Early Diagnosis                             0.0
Oral Cancer (Diagnosis)                     0.0
dtype: float64

In [ ]:
df['Country'].unique()

array(['Italy', 'Japan', 'UK', 'Sri Lanka', 'South Africa', 'Taiwan',
       'USA', 'Germany', 'France', 'Australia', 'Brazil', 'Pakistan',
       'Kenya', 'Russia', 'Nigeria', 'Egypt', 'India'], dtype=object)

In [18]:
pk_df = df[df["Country"] == 'Pakistan']

In [35]:
specs= pk_df[(pk_df['Betel Quid Use']=='Yes') & (pk_df['Oral Cancer (Diagnosis)']=='Yes') & (pk_df['Oral Lesions']=='Yes')]
survived = specs[specs['Survival Rate (5-Year, %)']>80]
died = specs[specs['Survival Rate (5-Year, %)']<80]

In [36]:
died

,ID,Country,Age,Gender,Tobacco Use,Alcohol Consumption,HPV Infection,Betel Quid Use,Chronic Sun Exposure,Poor Oral Hygiene,...,Difficulty Swallowing,White or Red Patches in Mouth,Tumor Size (cm),Cancer Stage,Treatment Type,"Survival Rate (5-Year, %)",Cost of Treatment (USD),Economic Burden (Lost Workdays per Year),Early Diagnosis,Oral Cancer (Diagnosis)
73,74,Pakistan,60,Male,No,No,Yes,Yes,Yes,No,...,Yes,Yes,4.220424,3,Targeted Therapy,45.399005,104777.75,71,Yes,Yes
1066,1067,Pakistan,34,Male,Yes,No,Yes,Yes,No,Yes,...,Yes,No,3.735199,4,No Treatment,23.362917,152858.00,100,Yes,Yes
1091,1092,Pakistan,56,Female,No,Yes,No,Yes,Yes,No,...,No,No,3.461421,4,Targeted Therapy,21.070555,66078.00,58,Yes,Yes
1195,1196,Pakistan,69,Male,Yes,Yes,Yes,Yes,No,Yes,...,No,Yes,4.600037,3,Radiation,37.879993,53364.50,43,Yes,Yes
1474,1475,Pakistan,62,Female,Yes,Yes,Yes,Yes,No,No,...,No,No,4.149583,2,Surgery,71.665600,111220.50,104,Yes,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84523,84524,Pakistan,55,Male,Yes,Yes,No,Yes,Yes,No,...,No,Yes,4.084319,3,No Treatment,39.237516,127008.00,149,Yes,Yes
84544,84545,Pakistan,70,Female,Yes,Yes,Yes,Yes,No,No,...,No,No,3.451305,3,Chemotherapy,36.285337,126880.25,89,Yes,Yes
84649,84650,Pakistan,62,Male,Yes,No,No,Yes,No,No,...,No,Yes,1.350367,2,Surgery,60.865569,43140.00,62,Yes,Yes
84711,84712,Pakistan,28,Male,No,Yes,Yes,Yes,Yes,No,...,No,Yes,1.552607,2,Chemotherapy,68.530561,32794.50,106,Yes,Yes
84766,84767,Pakistan,56,Male,Yes,Yes,No,Yes,No,No,...,No,Yes,4.582021,3,Radiation,49.453445,65002.00,89,Yes,Yes

In [38]:
died[died['Alcohol Consumption']=='Yes']

,ID,Country,Age,Gender,Tobacco Use,Alcohol Consumption,HPV Infection,Betel Quid Use,Chronic Sun Exposure,Poor Oral Hygiene,...,Difficulty Swallowing,White or Red Patches in Mouth,Tumor Size (cm),Cancer Stage,Treatment Type,"Survival Rate (5-Year, %)",Cost of Treatment (USD),Economic Burden (Lost Workdays per Year),Early Diagnosis,Oral Cancer (Diagnosis)
1091,1092,Pakistan,56,Female,No,Yes,No,Yes,Yes,No,...,No,No,3.461421,4,Targeted Therapy,21.070555,66078.00,58,Yes,Yes
1195,1196,Pakistan,69,Male,Yes,Yes,Yes,Yes,No,Yes,...,No,Yes,4.600037,3,Radiation,37.879993,53364.50,43,Yes,Yes
1474,1475,Pakistan,62,Female,Yes,Yes,Yes,Yes,No,No,...,No,No,4.149583,2,Surgery,71.665600,111220.50,104,Yes,Yes
2179,2180,Pakistan,54,Male,Yes,Yes,Yes,Yes,No,Yes,...,Yes,Yes,1.379581,2,Radiation,64.403522,99705.00,93,Yes,Yes
2246,2247,Pakistan,41,Male,Yes,Yes,No,Yes,No,Yes,...,No,No,4.732559,3,Surgery,47.987073,139604.50,175,Yes,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83953,83954,Pakistan,43,Male,Yes,Yes,No,Yes,No,Yes,...,No,No,1.726942,4,No Treatment,17.459167,90454.00,78,Yes,Yes
84523,84524,Pakistan,55,Male,Yes,Yes,No,Yes,Yes,No,...,No,Yes,4.084319,3,No Treatment,39.237516,127008.00,149,Yes,Yes
84544,84545,Pakistan,70,Female,Yes,Yes,Yes,Yes,No,No,...,No,No,3.451305,3,Chemotherapy,36.285337,126880.25,89,Yes,Yes
84711,84712,Pakistan,28,Male,No,Yes,Yes,Yes,Yes,No,...,No,Yes,1.552607,2,Chemotherapy,68.530561,32794.50,106,Yes,Yes
84766,84767,Pakistan,56,Male,Yes,Yes,No,Yes,No,No,...,No,Yes,4.582021,3,Radiation,49.453445,65002.00,89,Yes,Yes